PS-4482: item_geofunc_internal.h:163:60: error: 'box' may be used uninitialized
Replace envelope() with return_envelope() what quiets gcc-4.7.2 on debian:wheezy

Forward-ported from Percona Server 5.7 commit 6b874a491e803fc17c9cb093d142fec49a87291d as part of PS-269.
Produced by the PS-269 history split.