PS-5102: Merge MySQL 8.0.16 - router
PS-5724: Travis-CI: 8.0.16 MySQL Router does not build cleanly with clang 4 & 5

Turn off warnings for MySQL Router for clang-4 and clang-5 using the `-Wno-missing-braces` compiler flag.

PS-6058: gcc 5.5.0 compilation warnings for router

Fixed:
1.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc: In function ‘constexpr int o11x_version(TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc:99:57: error: expression ‘<throw-expression>’ is not a constant-expression
       throw std::invalid_argument("version out of range");
```
2.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc: In constructor ‘TlsServerContext::TlsServerContext(TlsVersion, TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc:67:43: error: statement has no effect [-Werror=unused-value]
   SSL_CTX_set_ecdh_auto(ssl_ctx_.get(), 1);
```